name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build and check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run Clippy
        run: cargo clippy
